### ISSUE TITLE
Does this book have english version?

### ISSUE THREAD

**Issue by afiq90** [KittenYang/A-GUIDE-TO-iOS-ANIMATION#3]
If I'm buying this book. Will i get an english version?

**Comment by KittenYang** [comment]
@afiq90  Oh,friend. I'm so eager to launch the English version,but I do not have so much energy to update the Chinese version  meanwhile publish the English version.Actually the Chinese version is also my part-time work.So,if I write this interactive book as a full-time job,I must publish the English version.
