### ISSUE TITLE
关于电子书的上得一个demo地址失效

### ISSUE THREAD

**Issue by ShixinPeng** [KittenYang/A-GUIDE-TO-iOS-ANIMATION#9]
hi
我最近在研习你的电子书上demo，但是第一节的demo地址失效了，我现在只能看这个demo，但是这个项目工程比较大，我没有清醒的思路，所以期望可以学习这个单节的demo
https://github.com/KittenYang/A-GUIDE-TO-iOS-ANIMATION/tree/master/AnimatedCircleDemo

**Comment by KittenYang** [comment]
不知道您想表达的意思。
